services:

  web:
    build: 
      context: ./
      dockerfile: dockerfile
    ports:
      - 8090:80
    volumes:
      - ./html:/usr/local/apache2/htdocs

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ta24alearndbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
volumes:
ta24alearndbdata: